# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pre-pull docker images
      run: |
        docker pull localstack/localstack
        docker pull tailscale/tailscale
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e .[dev]
    - name: Test with pytest
      run: |
        .venv/bin/pytest tests -o log_cli=true --capture no
      env:
        TS_AUTHKEY: "${{ secrets.TS_AUTHKEY }}"
